### ISSUE TITLE
[Feature Request] Start Session On System Login

### ISSUE THREAD

**Issue by elibroftw** [session-foundation/session-desktop#622]
A feature Discord, Matrix and even my music player is that they can start minimized to the tray after logging into the system.
Since you guys use electron, https://www.electronjs.org/docs/latest/api/app#appsetloginitemsettingssettings-macos-windows.

**Comment by Novack** [comment]
The original issue doesnt exist anymore, but there is no option for autostart, nor an option to autostart minimized. Any clues where I shall be looking?
